dir_names: 
  - acme
  - denisdebian.devops.rebrain.srwx.net
  - denisredhat.devops.rebrain.srwx.net 
virtualconf_ubuntu:
  - {src: 'virt_hosts.conf.j2', dest: '/etc/nginx/conf.d/{{ dir_names.1 }}.conf', mode: '0755'}
  - {src: 'index.html.j2', dest: '/opt/myprojects/{{ dir_names.1 }}/index.html', mode: '0644'}
virtualconf_centos:
  - {src: 'virt_hosts.conf.j2', dest: '/etc/nginx/conf.d/{{ dir_names.2 }}.conf', mode: '0755'}
  - {src: 'index.html.j2', dest: '/opt/myprojects/{{ dir_names.2 }}/index.html', mode: '0644'}
listen_http: 80
listen_http2: 443




